name: Run on All Branchess

on:
  push:
    branches:    
      - '*'  # Run on all branches
  pull_request:
    branches:
      - '*'  # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run a sample script
        run: echo "This runs on all branches!"
  pipeline_scan:
    # needs the build step before this job will start running
    needs: build
    runs-on: ubuntu-latest
    name: pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: verademo.war

      # run the pipeline scan action
      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@brand_logo
        with:
          vid: 'd7956013db5160e796033b7ff53e70e5'
          vkey: '48c52db689cde8468a270b0989ccbfb65c0dee4ff84cad4d2f3c2f25a5326a7f61d236677e267ce05e782a267746feb445ffe508000e482fd20a14262ee8a450'
          file: "verademo.war" 
